app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, abort, flash
from ..forms import FoodForm, DateForm, DayFoodForm, EditFoodForm, RegisterForm, LoginForm
from datetime import datetime
from ..models import User, Food, Log, LogFoodUser
from ..extensions import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user

main = Blueprint('main', __name__)

# For better modularization, auth shoulda been a separate blueprint.


@main.route("/register", methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        # return {
        #     "name": form.name.data,
        #     "username": form.username.data,
        #     "password": generate_password_hash(form.password.data)
        # }

        newUser = User(name=form.name.data,
                       username=form.username.data,
                       password=generate_password_hash(form.password.data))
        db.session.add(newUser)
        db.session.commit()
        login_user(newUser)
        return redirect(url_for("main.index"))

    return render_template('main/register.html', form=form)


@main.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # return {"username": form.username.data, "password": form.password.data}
        userToLogin = User.query.filter_by(username=form.username.data).first()
        if check_password_hash(userToLogin.password, form.password.data):
            login_user(userToLogin)
            flash('Logged ' + userToLogin.name + ' in successfully.')
            return redirect(url_for('main.index'))
        else:
            return "Wrong password, bucko.", 503
    return render_template('main/login.html', form=form)


@main.route("/logout", methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.login'))


@main.route("/help")
def help():
    return render_template('main/help.html')


@main.route("/", methods=['GET', 'POST'])
@login_required
def index():
    form = DateForm()

    if form.validate_on_submit():
        # return {"date": form.date.data.strftime("%B %m, %Y")}

        # Have to do a check to see if the date already exists to avoid duplicate date entries.
        newLog = Log(logDate=form.date.data)
        db.session.add(newLog)
        current_user.logs.append(newLog)
        db.session.commit()

        return redirect(url_for("main.index"))

    ############################################################################################
    ## SETTING THE LIMIT TO 5, BECAUSE IN REALITY THERE NEEDS TO BE PAGINATION OR SEARCH HERE ##
    ############################################################################################
    logList = current_user.logs[:]
    existingRecordsCount = len(logList[:])
    statsThisDate = {}
    for log in logList[-5:]:
        foodsids = LogFoodUser.query.filter_by(
            user_id=current_user.id).filter_by(log_id=log.id).all()
        foodsThisDate = []
        for fid in foodsids:
            foodsThisDate.append(Food.query.filter_by(id=fid.food_id).first())
        statsThisDate[log.id] = {"proteins": 0, "carbs": 0, "fats": 0}
        for food in foodsThisDate:
            statsThisDate[log.id]["proteins"] += food.proteins
            statsThisDate[log.id]["carbs"] += food.carbs
            statsThisDate[log.id]["fats"] += food.fats
    return render_template('main/index.html',
                           form=form,
                           logList=logList,
                           statsThisDate=statsThisDate,
                           existingRecordsCount=existingRecordsCount)


@main.route("/add", methods=['GET', 'POST'])
@login_required
def add():
    form = FoodForm()

    if form.validate_on_submit():
        # return {
        #     "name": form.name.data,
        #     "proteins": form.protein.data,
        #     "carbs": form.carbs.data,
        #     "fats": form.fats.data
        # }

        newFood = Food(name=form.name.data,
                       proteins=form.protein.data,
                       carbs=form.carbs.data,
                       fats=form.fats.data)

        db.session.add(newFood)
        db.session.commit()

        return redirect(url_for("main.add"))

    foodList = Food.query.all()
    ##############################################################################################
    # allowDelete:boolean - This is because there may be references to deletedFood in some dates #
    ##############################################################################################
    return render_template("main/add.html",
                           form=form,
                           foodList=foodList,
                           allowDelete=False)


@main.route("/edit/<foodid>", methods=['GET', 'POST'])
@login_required
def edit(foodid):
    form = FoodForm()
    foodToEdit = Food.query.filter_by(id=foodid).first()
    if form.validate_on_submit():
        foodToEdit.name = form.name.data
        foodToEdit.proteins = form.protein.data
        foodToEdit.carbs = form.carbs.data
        foodToEdit.fats = form.fats.data
        db.session.commit()
        return redirect(url_for("main.add"))
    return render_template("main/edit.html", form=form, foodToEdit=foodToEdit)


@main.route("/view/<dateid>", methods=['GET', 'POST'])
@login_required
def view(dateid):
    form = DayFoodForm()
    form.dayFood.choices = [(food.id, food.name)
                            for food in Food.query.order_by('name')]

    if form.validate_on_submit():
        # return {"food_id": form.dayFood.data, "log_id": dateid}
        foodToAdd = Food.query.filter_by(id=form.dayFood.data).first()
        LogToAddTo = Log.query.filter_by(id=dateid).first()
        newUserLogFood = LogFoodUser(log_id=LogToAddTo.id,
                                     food_id=foodToAdd.id,
                                     user_id=current_user.id)
        db.session.add(newUserLogFood)
        db.session.commit()
        return redirect(url_for('main.view', dateid=dateid))

    logDate = Log.query.filter_by(id=dateid).first()
    foodsids = LogFoodUser.query.filter_by(user_id=current_user.id).filter_by(
        log_id=dateid).all()
    foodsThisDate = []
    for fid in foodsids:
        foodsThisDate.append(Food.query.filter_by(id=fid.food_id).first())
    todayStats = {"proteins": 0, "carbs": 0, "fats": 0}
    for food in foodsThisDate:
        todayStats["proteins"] += food.proteins
        todayStats["carbs"] += food.carbs
        todayStats["fats"] += food.fats
    return render_template("main/view.html",
                           form=form,
                           logDate=logDate,
                           foodsThisDate=foodsThisDate,
                           todayStats=todayStats)


@main.route("/deleteFood/<foodid>")
@login_required
def deleteFood(foodid):
    foodToDelete = Food.query.filter_by(id=foodid).delete()
    db.session.commit()
    return redirect(url_for('main.add'))


@main.route("/deleteDayFood/<day>/<food>")
@login_required
def deleteDayFood(day, food):
    LogFoodUser.query.filter_by(food_id=food,
                                log_id=day,
                                user_id=current_user.id).delete()
    db.session.commit()
    return redirect(url_for('main.view', dateid=day))

app/templates/main/add.html
{% extends "base.html" %}
{% block title %} FoodTracker | Add Food Item {% endblock %}
{% block content %}
<div class="row t20">
	<div class="col-lg-8 col-lg-offset-2">
		<div class="panel panel-default">
			<div class="panel-body">
				<h3 class="lean-h text-black">
					<i class="glyphicon glyphicon-plus-sign"></i> New Food Form
				</h3>
				<hr />

				<form action="{{url_for('main.add')}}" method="POST">
					{{ form.csrf_token }}
					<div class="row">
						<div class="col-lg-6">
							<div class="form-group">
								{{ form.name.label }}
								{{ form.name(class='form-control', placeholder='Food name', autocomplete='off') }}
								{% if form.name.errors %}
								<ul>
									{% for error in form.name.errors %}
									<li>{{error}}</li>
									{% endfor %}
								</ul>
								{% endif %}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								{{ form.protein.label }}
								{{ form.protein(class='form-control', placeholder='Protein', autocomplete='off', min=0)
								}}
								{% if form.protein.errors %}
								<ul>
									{% for error in form.protein.errors %}
									<li>{{error}}</li>
									{% endfor %}
								</ul>
								{% endif %}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								{{ form.carbs.label }}
								{{ form.carbs(class='form-control', placeholder='Carbohydrates',
								autocomplete='off',min=0) }}
								{% if form.carbs.errors %}
								<ul>
									{% for error in form.carbs.errors %}
									<li>{{error}}</li>
									{% endfor %}
								</ul>
								{% endif %}
							</div>
						</div>


						<div class="col-lg-6">
							<div class="form-group">
								{{ form.fats.label }}
								{{ form.fats(class='form-control', placeholder='Fats', autocomplete='off', min=0) }}
								{% if form.fats.errors %}
								<ul>
									{% for error in form.fats.errors %}
									<li>{{error}}</li>
									{% endfor %}
								</ul>
								{% endif %}
							</div>
						</div>

						<div class="col-lg-12">
							<div class="form-group">
								<label style="visibility:hidden">submit</label>
								<button type="submit" class="btn btn-primary btn-block">
									<i class="glyphicon glyphicon-upload"></i> Submit
								</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<div class="row t20">
	<div class="col-lg-8 col-lg-offset-2">
		<div class="panel panel-default">
			<div class="panel-body">
				<h4 class="lean-h text-black">
					<i class="glyphicon glyphicon-th-list"></i> Existing Food Items
				</h4>
			</div>
			<div class="table-responsive">
				<table class="table table-striped table-hover table-bordered">
					<thead>
						<tr>
							<th style="width: 5%;">#</th>
							<th>Name</th>
							<th style="width: 10%;">Protein</th>
							<th style="width: 16%;">Carbohydrates</th>
							<th style="width: 10%;">Fat</th>
							<th style="width: 12%;">Calories</th>
							<th style="width: 20%;">Actions</th>
						</tr>
					</thead>
					<tbody>
						{% for food in foodList %}
						<tr>
							<td>{{ food.id }}</td>
							<td>{{ food.name }}</td>
							<td>{{ food.proteins }}</td>
							<td>{{ food.carbs }}</td>
							<td>{{ food.fats }}</th>
							<td>{{ food.carbs*4 + food.proteins*4 + food.fats*9 }}</td>
							<td>
								<a href="{{ url_for('main.edit', foodid=food.id) }}" class="btn btn-default btn-xs">
									<i class="glyphicon glyphicon-pencil"></i> Edit
								</a>
								{% if allowDelete %}
								<a href="{{ url_for('main.deleteFood', foodid=food.id) }}"
									class="btn btn-danger btn-xs">
									<i class="glyphicon glyphicon-trash"></i> Delete
								</a>
								{% endif %}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/main/edit.html
{% extends "base.html" %}
{% block title %} FoodTracker | Add Food Item {% endblock %}
{% block content %}
<div class="row t20">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3 class="lean-h text-black">
                    <i class="glyphicon glyphicon-plus-sign"></i> Edit {{ foodToEdit.name }}
                </h3>
                <hr />

                <form action="{{url_for('main.edit', foodid=foodToEdit.id)}}" method="POST">
                    {{ form.csrf_token }}
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                {{ form.name.label }}
                                {{ form.name(class='form-control', placeholder='Food Name', autocomplete='off',
                                value=foodToEdit.name)
                                }}
                                {% if form.name.errors %}
                                <ul>
                                    {% for error in form.name.errors %}
                                    <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                {{ form.protein.label }}
                                {{ form.protein(class='form-control', placeholder='Protein', autocomplete='off', min=0,
                                value=foodToEdit.proteins)
                                }}
                                {% if form.protein.errors %}
                                <ul>
                                    {% for error in form.protein.errors %}
                                    <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                {{ form.carbs.label }}
                                {{ form.carbs(class='form-control', placeholder='Carbohydrates',
                                autocomplete='off',min=0, value=foodToEdit.carbs) }}
                                {% if form.carbs.errors %}
                                <ul>
                                    {% for error in form.carbs.errors %}
                                    <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                {{ form.fats.label }}
                                {{ form.fats(class='form-control', placeholder='Fats', autocomplete='off', min=0,
                                value=foodToEdit.fats) }}
                                {% if form.fats.errors %}
                                <ul>
                                    {% for error in form.fats.errors %}
                                    <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block">
                                    <i class="glyphicon glyphicon-upload"></i> Submit the edit
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/help.html
{% extends "base.html" %}
{% block title %} FoodTracker | Help {% endblock %}
{% block content %}
<div class="container-fluid">
    <h3>It's simple really. 5Head</h3>
    <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Add Food</h5>
            </div>
            <p class="mb-1">In the Add Food Item page, you can generally add a food item that can be used by any person.
                You should do this if the food you want to add is not already on the list. </p>
        </a>
        <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Add a Log Date</h5>
            </div>
            <p class="mb-1"> When in homepage, you can select the Date input field and input a date and click on submit
                to add a Log Date.</p>
        </a>
        <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Add food to the added Log Date</h5>
            </div>
            <p class="mb-1"> Click on the view button in each of the log date cards in homepage.</p>
        </a>
    </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}
{% block title %} FoodTracker | Home {% endblock %}
{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<ul class="flashes">
	{% for message in messages %}
	<li>{{ message }}</li>
	{% endfor %}
</ul>
{% endif %}
{% endwith %}
<div class="row t20">
	<div class="col-lg-4 col-lg-offset-4">
		<div class="panel panel-default">
			<div class="panel-body">
				<form action="{{ url_for('main.index') }}" method="POST" role="form">
					{{ form.csrf_token }}
					<div class="form-group">
						<label><i class="glyphicon glyphicon-plus-sign"></i> Add New Date</label>
						<div class="input-group">
							{{ form.date(placeholder='Select New Date', class='form-control') }}
							<span class="input-group-btn">
								<button type="submit" class="btn btn-primary" id="add-btn">
									<i class="glyphicon glyphicon-plus-sign"></i> Add Date
								</button>
							</span>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<div class="row t20">
	<div class="col-lg-12">
		<h4 class="text-center text-white"><strong>Existing Records ({{existingRecordsCount}})</strong></h4>
	</div>
</div>

<div class="row t20">
	{% for log in logList %}
	<div class="col-lg-3">
		<div class="panel panel-warning">
			<div class="panel-body text-bold">
				<i class="glyphicon glyphicon-calendar"></i> {{log.logDate.strftime("%B %d, %Y")}}

				<a class="btn btn-primary btn-xs pull-right" href="{{url_for('main.view', dateid=log.id)}}">
					View <i class="glyphicon glyphicon-arrow-right"></i>
				</a>
			</div>
			<ul class="list-group">
				<li class="list-group-item text-bold"><span class="badge">{{statsThisDate[log.id].proteins}}</span>
					Protein</li>
				<li class="list-group-item text-bold"><span class="badge">{{statsThisDate[log.id].carbs}}</span>
					Carbohydrate</li>
				<li class="list-group-item text-bold"><span class="badge">{{statsThisDate[log.id].fats}}</span> Fat</li>
				<li class="list-group-item text-bold"><span class="badge">{{statsThisDate[log.id].proteins*4 +
						statsThisDate[log.id].carbs*4 + statsThisDate[log.id].fats*9}}</span> Calories</li>
			</ul>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

app/templates/main/login.html
{% extends "base.html" %}

{% block title %} Foodtracker | Login {% endblock %}

{% block content %}
<div class="row t20">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3 class="lean-h text-black">
                    <i class="glyphicon glyphicon-plus-sign"></i> wanna see ur tracking ?
                </h3>
                <hr />

                <form action="{{url_for('main.login')}}" method="POST">
                    {{ form.csrf_token }}
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                {{ form.username.label }}
                                {{ form.username(class='form-control', placeholder='username', autocomplete='off',
                                min=0)
                                }}
                                {% if form.username.errors %}
                                <ul>
                                    {% for error in form.username.errors %}
                                    <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                {{ form.password.label }}
                                {{ form.password(class='form-control', placeholder='Carbohydrates',
                                autocomplete='off',min=0) }}
                                {% if form.password.errors %}
                                <ul>
                                    {% for error in form.password.errors %}
                                    <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label style="visibility:hidden">submit</label>
                                <button type="submit" class="btn btn-primary btn-block">
                                    <i class="glyphicon glyphicon-upload"></i> Submit
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/register.html
{% extends "base.html" %}

{% block title %} Foodtracker | Login {% endblock %}

{% block content %}
<div class="row t20">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3 class="lean-h text-black">
                    <i class="glyphicon glyphicon-plus-sign"></i> New user in the need of some tracking ?
                </h3>
                <hr />

                <form action="{{url_for('main.register')}}" method="POST">
                    {{ form.csrf_token }}
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                {{ form.name.label }}
                                {{ form.name(class='form-control', placeholder='Full name', autocomplete='off') }}
                                {% if form.name.errors %}
                                <ul>
                                    {% for error in form.name.errors %}
                                    <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                {{ form.username.label }}
                                {{ form.username(class='form-control', placeholder='username', autocomplete='off',
                                min=0)
                                }}
                                {% if form.username.errors %}
                                <ul>
                                    {% for error in form.username.errors %}
                                    <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                {{ form.password.label }}
                                {{ form.password(class='form-control', placeholder='Carbohydrates',
                                autocomplete='off',min=0) }}
                                {% if form.password.errors %}
                                <ul>
                                    {% for error in form.password.errors %}
                                    <li>{{error}}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label style="visibility:hidden">submit</label>
                                <button type="submit" class="btn btn-primary btn-block">
                                    <i class="glyphicon glyphicon-upload"></i> Submit
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/view.html
{% extends "base.html" %}
{% block title %} FoodTracker | View Details {% endblock %}
{% block content %}

<div class="row t20">
	<div class="col-lg-4 col-lg-offset-4">
		<div class="panel panel-default">
			<div class="panel-body">
				<form action="{{ url_for('main.view', dateid=logDate.id) }}" method="POST" role="form">
					{{ form.csrf_token }}
					<div class="form-group">
						{{ form.dayFood.label }}
						<div class="input-group">
							{{ form.dayFood(class='form-control') }}
							<span class="input-group-btn">
								<button type="submit" class="btn btn-primary" id="add-btn">
									<i class="glyphicon glyphicon-plus-sign"></i> Add Food
								</button>
							</span>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<div class="row t20">
	<div class="col-lg-8 col-lg-offset-2">
		<div class="panel panel-default">
			<div class="panel-body">
				<h3 class="lean-h text-black">
					<i class="glyphicon glyphicon-calendar"></i> {{ logDate.logDate.strftime('%B %d, %Y') }}
				</h3>

				<div class="row">
					<div class="col-lg-3">
						<h4 class="lean-h">
							Protein: &nbsp;<strong class="f25">{{todayStats.proteins}}</strong>
						</h4>
					</div>
					<div class="col-lg-3">
						<h4 class="lean-h">
							Carbohydrates: <strong class="f25">{{todayStats.carbs}}</strong>
						</h4>
					</div>
					<div class="col-lg-3">
						<h4 class="lean-h">
							Fat: <strong class="f25">{{todayStats.fats}}</strong>
						</h4>
					</div>
					<div class="col-lg-3">
						<h4 class="lean-h">
							Calories: <strong class="f25">{{todayStats.proteins*4 + todayStats.carbs*4 +
								todayStats.fats*9}}</strong>
						</h4>
					</div>
				</div>
			</div>
			<div class="table-responsive">
				<table class="table table-striped table-hover table-bordered">
					<thead>
						<tr>
							<th style="width: 5%;">#</th>
							<th>Name</th>
							<th style="width: 10%;">Protein</th>
							<th style="width: 16%;">Carbohydrates</th>
							<th style="width: 10%;">Fat</th>
							<th style="width: 12%;">Calories</th>
							<th style="width: 20%;">Actions</th>
						</tr>
					</thead>
					<tbody>
						{% for food in foodsThisDate %}
						<tr>
							<td>{{ food.id }}</td>
							<td>{{ food.name }}</td>
							<td>{{ food.proteins }}</td>
							<td>{{ food.carbs }}</td>
							<td>{{ food.fats }}</th>
							<td>{{ food.carbs*4 + food.proteins*4 + food.fats*9 }}</td>
							<td>
								<a href="{{ url_for('main.deleteDayFood', day=logDate.id, food=food.id) }}"
									class="btn btn-danger btn-xs">
									<i class="glyphicon glyphicon-trash"></i> Delete
								</a>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
{% endblock %}